### ISSUE TITLE
[Not an issue] Here are Datasets in HF datasets format

### ISSUE THREAD

**Issue by TalhaUsuf** [KiseKloset/DM-VTON#10]
**This is not an issue**
----
I converted your datasets into HF datasets format for ease of use and easy pulling/processing:

Train split:
-----------
```bash
SaffalPoosh/DM-vton-train
```

Test split:
-----------
```bash
SaffalPoosh/DM-vton-test
```

Thanks ⚡

**Comment by zero-nnkn** [comment]
Hey @TalhaUsuf, did you convert the dataset to HuggingFace (HF?)

**Comment by zero-nnkn** [comment]
Can you provide guidance "how to use HF dataset" with our training scripts?

**Comment by TalhaUsuf** [comment]
I am making changes accordingly, will make pull request.
Thanks for your good research.
