### ISSUE TITLE
Reproduce result in paper

### ISSUE THREAD

**Issue by npk7264** [KiseKloset/DM-VTON#11]
I have trained by using a file notebook, but in stage 2 of Teacher, it's running out of GPU memory.
I reduced batch_size from 14 to 12. However, FID ~ 60.
Could you let me know your config, GPU, and parameters when training to have FID ~ 28 as paper? Thank you.

**Comment by zero-nnkn** [comment]
In Colab, we demo how to train the model and the used resource. So, we set the total epochs for each stage as 2 (`niter=1` and `niter_decay=1`).
If you want to reproduce, please follow the report in the [paper](https://arxiv.org/abs/2308.13798) using 100 epochs (`niter=50` and `niter_decay=50`) for each stage.
