### ISSUE TITLE
Use on custom images

### ISSUE THREAD

**Issue by benemana** [KiseKloset/DM-VTON#14]
Hi, is it possible to use the model on some custom images, both for person and garment? Can you please provide some guidance? Thank you

**Comment by zero-nnkn** [comment]
Hello, please follow the inference guide in our [Colab Notebook](https://colab.research.google.com/drive/1oLg0qe0nqLuIeaklzwbkk3IOKmMb0clk). Just replace the `data_root` param with your data directory.
