### ISSUE TITLE
好像 安装不了。scripts/install.sh这是linux的命令...🍎电脑和linux系统电脑才能跑。我是window

### ISSUE THREAD

**Issue by psksiu** [KiseKloset/DM-VTON#16]
好像 安装不了。scripts/install.sh这是linux的命令...🍎电脑和linux系统电脑才能跑。我是window

**Comment by zero-nnkn** [comment]
We have only tested these scripts on linux. If you use windows, I suggest using [WSL](https://learn.microsoft.com/en-us/windows/wsl/install).
