### ISSUE TITLE
Dress Code dataset

### ISSUE THREAD

**Issue by mirfan899** [KiseKloset/DM-VTON#18]
Is it possible to use dress code dataset as well as viton dataset??

**Comment by zero-nnkn** [comment]
Yes, please check our [dresscode dataloader](https://github.com/KiseKloset/DM-VTON/blob/main/dataloader/dresscode_dataset.py).
Note that we resize the image size to (256, 192).

**Comment by arifshahriarnsl** [comment]
@zero-nnkn Can i used the original dresscode/Viton dataset resolution for training Teacher and Student model?. Please help.
