### ISSUE TITLE
Pre-trained pb checkpoints

### ISSUE THREAD

**Issue by serdarnazli** [KiseKloset/DM-VTON#21]
Is it possible for us to obtain pre-trained pb checkpoints? Training the teacher model from scratch is time consuming making further research less viable

**Comment by rusenbb** [comment]
Hey maintainers! 🙌

I couldn't agree more with the original poster. Training the Teacher model from scratch is a huge time sink, and it's holding back a lot of us who are itching to dive into the exciting parts of DM-VTON research. 

It would make the project way more accessible and allow us to focus on pushing the boundaries of what's possible. 
I know it's extra work, but I genuinely believe it would supercharge innovation and collaboration in the community. 

So, pretty please, could you consider sharing those pre-trained pb checkpoints? It would mean the world to us! 🙏

Thanks for all your hard work and for considering this request. You're awesome! 😄

Cheers

**Comment by zero-nnkn** [comment]
Thank you for your interest in the research. I created a release [1.0.0](https://github.com/KiseKloset/DM-VTON/releases/tag/1.0.0) with the teacher/student pretrained checkpoints that were reported in the paper.
I hope it will be useful.
