### ISSUE TITLE
What is .npy files used for VITON-HD dataset?

### ISSUE THREAD

**Issue by KIRAN-MK-211** [KiseKloset/DM-VTON#3]
Great work!. @KiseKloset. Is the .npy files used in the training and inference same numpy array of the images that densepose generate?

**Comment by pntt3011** [comment]
Hi @KIRAN-MK-211, we just upload the DensePose we used at https://github.com/KiseKloset/densepose. Hope this help.

**Comment by KIRAN-MK-211** [comment]
Thank you.
