### ISSUE TITLE
Tutorial on how to use this 

### ISSUE THREAD

**Issue by sudip550** [KiseKloset/DM-VTON#7]
Can you please provide tutorial on how to use your colab...

**Comment by zero-nnkn** [comment]
Hi @sudip550, 
We have the instructions in the `README`. The colab file just follow those instructions (with some explanations in both training and testing phases).
Can you tell us which step you got stuck (or the problems with document) so we can improve it?

**Comment by zero-nnkn** [comment]
I will close this issue. 
Feel free to re-open it if you have any problems with documents,
